MODEL:
  VID:
    METHOD: "rdn"
    ROI_BOX_HEAD:
      ATTENTION:
        ENABLE: True
  META_ARCHITECTURE: "GeneralizedRCNNRDN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "RDNFeatureExtractor"
    PREDICTOR: "FPNPredictor"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, )
  MAX_ITER: 120000
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 500
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_videos",)