MODEL:
  VID:
    METHOD: "rdn"
    ROI_BOX_HEAD:
      ATTENTION:
        ENABLE: True
  META_ARCHITECTURE: "GeneralizedRCNNRDN"
  WEIGHT: "/data7/djiajun/video_detection/pretrained_models/R-101.pkl"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "RDNFeatureExtractor"
    PREDICTOR: "FPNPredictor"
INPUT:
  WITH_AUGMENTATION: True
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_videos",)
OUTPUT_DIR: "./outputs/20200328/RDN_base_1x"